apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus-apigee-exporter.fullname" . }}-blackbox
  labels:
    {{- include "prometheus-apigee-exporter.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9115
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "prometheus-apigee-exporter.selectorLabels" . | nindent 4 }}